services:
  catalogdb:
    image: postgres
  basketdb:
    image: postgres
# La base de datos y los volumenes deben estar al mismo con los servicos
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalag/Catalog.API/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
